spring.application.name=dcas

spring.datasource.url=jdbc:mysql://mysql-doctor-commission.c3ics2yysurh.eu-north-1.rds.amazonaws.com:3306/dcas_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=admin
spring.datasource.password=root1234
spring.jpa.hibernate.ddl-auto=update

# H2 console disabled when using MySQL
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console
